plugins {
    id 'java'
    id 'org.jetbrains.kotlin.jvm'
}


dependencies {
    implementation 'org.JVM-austral:ast:1.1.14'
    implementation 'org.JVM-austral:cli:1.1.14'
    implementation 'org.JVM-austral:common:1.1.14'
    implementation 'org.JVM-austral:formatter:1.1.14'
    implementation 'org.JVM-austral:interpreter:1.1.14'
    implementation 'org.JVM-austral:lexer:1.1.14'
    implementation 'org.JVM-austral:linter:1.1.14'
    implementation 'org.JVM-austral:parser:1.1.14'
    implementation 'org.JVM-austral:runner:1.1.14'
    implementation 'org.JVM-austral:token:1.1.14'
}


repositories {
    mavenLocal()
    mavenCentral()
    maven {
        name = "GitHubPackages"
        url = uri("https://maven.pkg.github.com/JVM-austral/tp-ingsis-interpreter")
        credentials {
            username = project.findProperty("gpr.user") ?: System.getenv("USERNAME")
            password = project.findProperty("gpr.key") ?: System.getenv("TOKEN")
        }
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

test {
    minHeapSize = "5m" // initial heap size
    maxHeapSize = "7m" // maximum heap size
}

dependencies {
    testImplementation 'junit:junit:4.13.1'
}

test {
    environment "BEST_FOOTBALL_CLUB", "San Lorenzo"
    useJUnit()
}
